// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFuo3EXYNXDugJmg2VAWG37_ojtsB8Kfc',
    appId: '1:647457575978:web:c05a87dcdda9a1e7505f53',
    messagingSenderId: '647457575978',
    projectId: 'beautyxp-2026-2cf78',
    authDomain: 'beautyxp-2026-2cf78.firebaseapp.com',
    storageBucket: 'beautyxp-2026-2cf78.firebasestorage.app',
    measurementId: 'G-70WBPQ0PPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmGYiMmUjwU0EA22kywMjBMqd5BQMo_s',
    appId: '1:647457575978:android:c1e28e6f09fb47ca505f53',
    messagingSenderId: '647457575978',
    projectId: 'beautyxp-2026-2cf78',
    storageBucket: 'beautyxp-2026-2cf78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0yd8bMczeudD2ateDD27ZA_xvz3ZJ04',
    appId: '1:647457575978:ios:330321ed64a192f4505f53',
    messagingSenderId: '647457575978',
    projectId: 'beautyxp-2026-2cf78',
    storageBucket: 'beautyxp-2026-2cf78.firebasestorage.app',
    iosBundleId: 'com.example.beautyxpFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt0yd8bMczeudD2ateDD27ZA_xvz3ZJ04',
    appId: '1:647457575978:ios:330321ed64a192f4505f53',
    messagingSenderId: '647457575978',
    projectId: 'beautyxp-2026-2cf78',
    storageBucket: 'beautyxp-2026-2cf78.firebasestorage.app',
    iosBundleId: 'com.example.beautyxpFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFuo3EXYNXDugJmg2VAWG37_ojtsB8Kfc',
    appId: '1:647457575978:web:7322fdf48dc1f7bb505f53',
    messagingSenderId: '647457575978',
    projectId: 'beautyxp-2026-2cf78',
    authDomain: 'beautyxp-2026-2cf78.firebaseapp.com',
    storageBucket: 'beautyxp-2026-2cf78.firebasestorage.app',
    measurementId: 'G-PTJJ298R92',
  );
}
